### PR TITLE
fix non-positive durations for metrics

### PR DESCRIPTION
**Pull request by malafeev**
- deleted unused `rc/main/java/com/lightstep/tracer/metrics/SafeMetrics.java` and corresponding test class
-  duration of first report is 0 therefore I drop it. It happens not only on start up because we kill metrics reporting thread if there are no traces during timeout and then start again if there are. So when we again start thread duration of first report is 0, so drop it. This should fix non-positive duration.

### CODE REVIEW

**Comment by andrewhsu** [comment]
Talked to @malafeev, could use test case, comments in the commit, and possibly a check for positive value.

**Comment by carlosalberto** [comment]
Overall it looks great. Only two things I'd like to be verified:

1. Not sending the first report *ever* used to break the metrics tests. I saw you changed the metrics counts in a few tests, to correct this. Would you mind running the tests many times to verify they are still correct? (the tests are rather flaky, but still).

2. I'd like to see this tested against the actual backend. As you don't have experience using the RCA metrics on the backend, lets coordinate offline to make that happen ;)

**Comment by malafeev** [comment]
1. yes, I ran it many times locally, looks stable. But all these sleeps can potentially produce false positives.
2. I didn't see metrics in UI, probably not enough permissions

**Comment by malafeev** [comment]
I see metrics :)
Screen Shot 2020-06-12 at 14 58 20

**Comment by carlosalberto** [comment]
Let's give it a run!

**Pull request merged**
